import pandas as pd
allMembers = {
    'sender': [
        'Abhik Nhs',
        'Anirban Majumdar Nhs',
        'Anish Nhs',
        'Ayan Nhs',
        'Babu NHS',
        'Bappa Nhs',
        'Bishwa Nhs',
        'Debanjan Nhs',
        'Debashish Nhs',
        'Debmalya Thapa 2',
        'Dibendu Khaskel Nhs',
        'Dip Chakraborty',
        'Dodo Santanu',
        'Dr Sudip Nhs',
        'Gana',
        'Hasan',
        'Holder Debabrata Nhs',
        'Jyotirmoy Sharma',
        'Krishanu Nhs',
        'Kundu Debabrata Nhs',
        'Lattu Nhs',
        'Nayek NHS',
        'Nilanjan Nhs',
        'Palash Nhs',
        'Partha NHS',
        'Piyas Nhs',
        'Prabir NHS',
        'Prez',
        'Rajib Nhs Das',
        'Raju Datta Nhs',
        'Rana NHS',
        'Sanjoy Kajol Nhs',
        'Sayan Nhs',
        'Somenath Nhs',
        'Sonai',
        'Soumya Nhs',
        'Souvik Nhs',
        'Subhomoy Nhs',
        'Sudip nhs',
        'Sujoy NHS',
        'Sukanto NHS',
        'Sumit Nhs',
        'Susanta Das Nhs',
        'Sutanu Nhs',
        'Suvankar? Nhs',
        'Tuhin Das Nhs',
        'Tushar Maji Nhs',
        'Ujjal Kumar Chakraborty',
        'rudra NHS',
        'ফড়ে Subho Nhs']

}
# allMembers = {'sender': []}
allMembersdf = pd.DataFrame(allMembers, columns=['sender'])
